[package]
name = "jumper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
home = "0"
regex = "1"
dirs = "5"
tempfile = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
whoami = "1"
lazy_static = "1"
